#!/bin/bash -l

# Check that updates have been made to `hashicups/resource_order.go`
if ! grep -q 'ResourceImporter' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to update the 'resourceOrder' function in 'hashicups/resource_order.go' using the code example."
    exit 1
fi

if [ ! -f $TF_IMPORT_MAIN_FILE ]; then
    fail-message "You have not created the 'main.tf' file under the 'examples/import' directory yet."
    exit 1
fi

# Check the contents of the main.tf file
if ! grep -q 'sample_order' "$TF_IMPORT_MAIN_FILE"; then
    fail-message "You need to add the sample order to import to in '$TF_IMPORT_MAIN_FILE'."
    exit 1
fi

# Check the state file and see that something has been imported (isn't ID #1)
LAST_RESOURCE_ID=$(cat terraform.tfstate | jq -r .resources[0].instances[-1].attributes.id)
if [ "$LAST_RESOURCE_ID" = "1" ]; then
    fail-message "You did not successfully import the resource to your Terraform state."
    exit 1
fi
