#!/bin/bash -l

# Check out the branch with all the correct files
cd $PROJECT_HOME_DIR
git checkout implement-create

# Create an order via the API
curl -X POST -H "Authorization: ${HASHICUPS_TOKEN}" localhost:19090/orders -d '[{"coffee": { "id":1 }, "quantity":4}, {"coffee": { "id":3 }, "quantity":3}]'

# Install the provider
make instruqt_install

# Initialize and apply
cd $PROJECT_HOME_DIR/examples
terraform init && terraform apply -auto-approve

exit 0
