#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

# Run the check for curl
curl localhost:19090/health

# Check out the branch with all the correct files
cd $PROJECT_HOME_DIR
git checkout implement-read

# Initialize the module for our provider and install the dependencies.
go mod init terraform-provider-hashicups
go mod vendor

# Install the provider
make instruqt_install

# Initialize and apply
cd $PROJECT_HOME_DIR/examples
terraform init && terraform apply -auto-approve

exit 0
