#!/bin/bash -l

if ! grep -q 'last_updated' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'last_updated' schema to the 'resourceOrder' in '$RESOURCE_ORDER_FILE'."
    exit 1
fi

# Check that the resourceOrderUpdate function was implemented (not just present)
if ! grep -q 'c.UpdateOrder(orderID, ois)' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to implement the resourceOrderUpdate function in '$RESOURCE_ORDER_FILE'."
    exit 1
fi

# Check for the new imports
if ! grep -q 'time' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'time' import in '$RESOURCE_ORDER_FILE'."
    exit 1
fi

# Check the `main.tf` file has the update quantity within the hashicups_order resource
if ! grep -q 'quantity = 3' "$TF_MAIN_FILE"; then
    fail-message "You need to change the quantity from 2 to 3 in the 'hashicups_order' resource in '$TF_MAIN_FILE'."
    exit 1
fi

# Check that the order was successfully updated to the new quantity
cd $PROJECT_HOME_DIR/examples
SECOND_COFFEE_QUANTITY=$(terraform output -json | jq -r .edu_order.value.items[1].quantity)
if ! [ "$SECOND_COFFEE_QUANTITY" = "3" ]; then
    fail-message "You did not successfully add the new outputs to your Terraform configuration."
    exit 1
fi
