# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/hashistack-0-14-0
  shell: /bin/bash
  machine_type: n1-standard-2
